/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TContainsall extends Token
{
    public TContainsall()
    {
        super.setText("containsall");
    }

    public TContainsall(int line, int pos)
    {
        super.setText("containsall");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TContainsall(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTContainsall(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TContainsall text.");
    }
}
