/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TContainsentry extends Token
{
    public TContainsentry()
    {
        super.setText("containsentry");
    }

    public TContainsentry(int line, int pos)
    {
        super.setText("containsentry");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TContainsentry(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTContainsentry(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TContainsentry text.");
    }
}
