/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TContains extends Token
{
    public TContains()
    {
        super.setText("contains");
    }

    public TContains(int line, int pos)
    {
        super.setText("contains");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TContains(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTContains(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TContains text.");
    }
}
