/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TCount extends Token
{
    public TCount()
    {
        super.setText("count");
    }

    public TCount(int line, int pos)
    {
        super.setText("count");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCount(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCount(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCount text.");
    }
}
