/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TGet extends Token
{
    public TGet()
    {
        super.setText("get");
    }

    public TGet(int line, int pos)
    {
        super.setText("get");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGet(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGet(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGet text.");
    }
}
