/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class THas extends Token
{
    public THas()
    {
        super.setText("has");
    }

    public THas(int line, int pos)
    {
        super.setText("has");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THas(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHas(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THas text.");
    }
}
