/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class THasall extends Token
{
    public THasall()
    {
        super.setText("hasall");
    }

    public THasall(int line, int pos)
    {
        super.setText("hasall");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THasall(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHasall(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THasall text.");
    }
}
