/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class THasentry extends Token
{
    public THasentry()
    {
        super.setText("hasentry");
    }

    public THasentry(int line, int pos)
    {
        super.setText("hasentry");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THasentry(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHasentry(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THasentry text.");
    }
}
