/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TIndex extends Token
{
    public TIndex()
    {
        super.setText("index");
    }

    public TIndex(int line, int pos)
    {
        super.setText("index");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIndex(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIndex(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIndex text.");
    }
}
