/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TKeys extends Token
{
    public TKeys()
    {
        super.setText("keys");
    }

    public TKeys(int line, int pos)
    {
        super.setText("keys");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKeys(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeys(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKeys text.");
    }
}
