/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TMagic extends Token
{
    public TMagic()
    {
        super.setText("magic");
    }

    public TMagic(int line, int pos)
    {
        super.setText("magic");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMagic(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMagic(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMagic text.");
    }
}
