/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TRemove extends Token
{
    public TRemove()
    {
        super.setText("remove");
    }

    public TRemove(int line, int pos)
    {
        super.setText("remove");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRemove(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRemove(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRemove text.");
    }
}
