/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TRemoveall extends Token
{
    public TRemoveall()
    {
        super.setText("removeall");
    }

    public TRemoveall(int line, int pos)
    {
        super.setText("removeall");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRemoveall(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRemoveall(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRemoveall text.");
    }
}
