/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TRemall extends Token
{
    public TRemall()
    {
        super.setText("remall");
    }

    public TRemall(int line, int pos)
    {
        super.setText("remall");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRemall(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRemall(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRemall text.");
    }
}
