/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TRem extends Token
{
    public TRem()
    {
        super.setText("rem");
    }

    public TRem(int line, int pos)
    {
        super.setText("rem");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRem(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRem(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRem text.");
    }
}
