/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TTuple extends Token
{
    public TTuple()
    {
        super.setText("tuple");
    }

    public TTuple(int line, int pos)
    {
        super.setText("tuple");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTuple(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTuple(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTuple text.");
    }
}
