/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TUnpack extends Token
{
    public TUnpack()
    {
        super.setText("unpack");
    }

    public TUnpack(int line, int pos)
    {
        super.setText("unpack");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnpack(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnpack(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUnpack text.");
    }
}
