/* This file was generated by SableCC (http://www.sablecc.org/). */

package dssl.node;

import dssl.analysis.*;

@SuppressWarnings("nls")
public final class TValues extends Token
{
    public TValues()
    {
        super.setText("values");
    }

    public TValues(int line, int pos)
    {
        super.setText("values");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TValues(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTValues(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TValues text.");
    }
}
